"""Connector manifest to ontology pack compilation (AU-BOUNDARY-R030).

The SDK half of "hand-written ontology emitters behind EG pack compilation":
``agent_utilities.knowledge_graph.ontology.manifest_compiler`` (AU) compiled a
:class:`~agent_connector_sdk.manifest.model.ConnectorManifest` into Turtle by
hand; this module is the typed, source-agnostic replacement every connector
calls through this SDK instead. AU's compile-before-sync gate calls
:func:`compile_manifest_ontology` on its own manifest (re-validated against
this SDK's :class:`~agent_connector_sdk.manifest.model.ConnectorManifest`) and
hashes the result the same way it hashed its own hand-rendered Turtle, so the
compile-before-sync and integrity checks this SDK's callers rely on keep
behaving identically while AU's copy of the emitter is retired.

Pure, deterministic, zero LLM calls and no network I/O: every class, object
property, and datatype property below is a direct structural projection of the
manifest's own declared ``resources``/``schema_mappings`` fields.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .model import ConnectorManifest

__all__ = [
    "OntologyClassSpec",
    "OntologyDatatypePropertySpec",
    "OntologyObjectPropertySpec",
    "OntologySpec",
    "compile_manifest_ontology",
    "compile_manifest_ontology_spec",
]


@dataclass
class OntologyClassSpec:
    """One connector resource as an OWL class."""

    local: str
    label: str
    parent: str | None
    id_prefix: str


@dataclass
class OntologyObjectPropertySpec:
    """One cross-resource relation as an OWL object property."""

    local: str
    label: str
    domain: str | None
    range: str
    lpg_rel_type: str


@dataclass
class OntologyDatatypePropertySpec:
    """One record field as an OWL datatype property (ontology-wide, no domain)."""

    local: str
    label: str
    range: str


@dataclass
class OntologySpec:
    """The compiled manifest: OWL terms plus the maps a connector consumes."""

    classes: list[OntologyClassSpec] = field(default_factory=list)
    object_properties: list[OntologyObjectPropertySpec] = field(default_factory=list)
    datatype_properties: list[OntologyDatatypePropertySpec] = field(
        default_factory=list
    )
    # resource local name -> (owl class local, node-id prefix)
    type_map: dict[str, tuple[str, str]] = field(default_factory=dict)
    # relation local name -> (lpg_rel_type, target resource)
    relation_map: dict[str, tuple[str, str]] = field(default_factory=dict)


def _humanize(camel: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", camel)
    return s[:1].upper() + s[1:] if s else s


def _upper_snake(name: str) -> str:
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return s.upper()


def compile_manifest_ontology_spec(manifest: ConnectorManifest) -> OntologySpec:
    """Compile a :class:`ConnectorManifest` into a source-agnostic :class:`OntologySpec`."""
    spec = OntologySpec()
    seen_dtp: set[str] = set()

    for resource in manifest.resources:
        mapping = manifest.schema_mappings.get(resource.name)
        parent = mapping.ontology_class if mapping else None
        id_prefix = resource.id_prefix or resource.name.lower()
        spec.classes.append(
            OntologyClassSpec(
                local=resource.name,
                label=resource.label or _humanize(resource.name),
                parent=parent,
                id_prefix=id_prefix,
            )
        )
        spec.type_map[resource.name] = (resource.name, id_prefix)

        if mapping is not None:
            for fname, xsd in mapping.fields.items():
                if fname in seen_dtp:
                    continue
                seen_dtp.add(fname)
                spec.datatype_properties.append(
                    OntologyDatatypePropertySpec(
                        local=fname, label=_humanize(fname), range=xsd
                    )
                )

        for rel in resource.relations:
            lpg = rel.lpg_rel_type or _upper_snake(rel.name)
            spec.object_properties.append(
                OntologyObjectPropertySpec(
                    local=rel.name,
                    label=rel.label or _humanize(rel.name),
                    domain=resource.name,
                    range=rel.target,
                    lpg_rel_type=lpg,
                )
            )
            spec.relation_map[rel.name] = (lpg, rel.target)

    return spec


def _ttl_header(source: str) -> str:
    return f"""\
# GENERATED by agent_connector_sdk.manifest.ontology_pack from
# connector_manifest.yml. Do not edit by hand — regenerate via
# ``scripts/generate_connector_manifests.py --connector {source}``.
# CONCEPT:AU-BOUNDARY-R030.
@prefix : <http://knuckles.team/kg#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://knuckles.team/kg/{source}> a owl:Ontology ;
    rdfs:label "{source} Ontology (generated)" ;
    rdfs:comment "OWL mirror of the {source} connector manifest — every resource, relation, and field. CONCEPT:AU-BOUNDARY-R030." ;
    owl:imports <http://knuckles.team/kg> .
"""


def _export_ontology_ttl(spec: OntologySpec, *, source: str) -> str:
    lines: list[str] = [_ttl_header(source)]

    for c in sorted(spec.classes, key=lambda x: x.local):
        block = [f":{c.local} a owl:Class ;", f'    rdfs:label "{c.label}" ;']
        if c.parent:
            block.append(f"    rdfs:subClassOf :{c.parent} ;")
        block.append('    rdfs:comment "Connector resource (generated)." .')
        lines.append("\n".join(block))

    for p in sorted(spec.object_properties, key=lambda x: (x.local, x.domain or "")):
        rng = p.range if p.range == "owl:Thing" else f":{p.range}"
        block = [f":{p.local} a owl:ObjectProperty ;", f'    rdfs:label "{p.label}" ;']
        if p.domain:
            block.append(f"    rdfs:domain :{p.domain} ;")
        block.append(f"    rdfs:range {rng} .")
        lines.append("\n".join(block))

    for d in sorted(spec.datatype_properties, key=lambda x: x.local):
        lines.append(
            f":{d.local} a owl:DatatypeProperty ;\n"
            f'    rdfs:label "{d.label}" ;\n'
            f"    rdfs:range {d.range} ."
        )

    return "\n\n".join(lines) + "\n"


def compile_manifest_ontology(manifest: ConnectorManifest) -> str:
    """Compile a :class:`ConnectorManifest` straight to Turtle (AU-BOUNDARY-R030).

    The single entry point a connector-sync gate calls: it replaces AU's
    hand-maintained ``compile_manifest`` + ``export_manifest_ttl`` pair
    (``agent_utilities.knowledge_graph.ontology.manifest_compiler``) with one
    typed pipeline a connector reaches only through this SDK.
    """
    spec = compile_manifest_ontology_spec(manifest)
    return _export_ontology_ttl(spec, source=manifest.resolved_ontology_source)
